REM Initialize CPU Registers
REM 15-Bit Regsiters
DIM ACR AS INTEGER            ' ACR = Accumulator Register
DIM HCR AS INTEGER            ' HCR = Holding Cell Register
DIM BVR AS INTEGER            ' BVR = Bravo Register
DIM CHR AS INTEGER            ' CHR = Charlie Register 
REM 12-Bit Registers
DIM PCR AS INTEGER            ' PCR = Program Counter Register
DIM MAR AS INTEGER            ' MAR = Memory Address Register
DIM AIR AS INTEGER            ' AIR = Address Input Register
REM 3-Bit Registers
DIM OIR AS INTEGER            ' OIR = OpCode Input Register
REM 1-Bit Status Registers
DIM CAR AS INTEGER            ' CAR = Carry Flag
DIM ZER AS INTEGER            ' ZER = Zero Flag
DIM MRD AS INTEGER            ' MRD = Memory Ready Flag

